### ISSUE TITLE
Low Memory Error

### ISSUE THREAD

**Issue by fefsf** [nicehash/ccminer-x11gost#1]
Running more than 4 cards results in cuda low memory errors. I have a 6 card 1070 rig. I disabled X11GOST on two of the gpus in the settings, but then when those two cards tried to mine EQM the EQM miner reported low memory errors. Enabling X11GOST on only 3 GPUs has resolved the problem for now. My rig has 8GB of RAM.

The first time i tried mining with all 6 cards i received the error within the miner, as well as an error in windows itself claiming low memory available.

**Comment by kenshirothefist** [comment]
For multi-GPU systems, set Virtual Memory size in Windows at least 16 GB:
"Computer Properties / Advanced System Settings / Performance / Advanced / Virtual Memory".

**Comment by fefsf** [comment]
kenshirothefist, thank you. That worked great.

**Comment by kenshirothefist** [comment]
@fefsf Happy to help.
